
POST http://localhost:5000/file?name=abc&content=Hello 

###
POST http://localhost:5000/folder?name=abc

###
PUT http://localhost:5000/file?oldname=abc.txt&newname=def.txt

###
PUT http://localhost:5000/folder?oldfolder=abc&newfolder=def

###

